SELECT NAME FROM PLAYERS where
PLAYERNO IN (SELECT PLAYERNO FROM MATCHES where TEAMNO = 1)
AND 
PLAYERNO IN (SELECT PLAYERNO FROM MATCHES where TEAMNO = 2);

SELECT NAME, INITIALS FROM PLAYERS where PLAYERNO NOT IN
(SELECT PLAYERNO FROM PENALTIES where to_char(PEN_DATE, 'yyyy') = '1980');

SELECT * FROM PLAYERS where PLAYERNO IN (SELECT PLAYERNO FROM PENALTIES where AMOUNT > 80);

SELECT * FROM PLAYERS where PLAYERNO 
IN (SELECT PLAYERNO FROM PENALTIES where AMOUNT > 80) 
AND PLAYERNO NOT IN (SELECT PLAYERNO FROM PENALTIES where AMOUNT <= 80);

SELECT * FROM EMP e where SAL > 
(SELECT AVG(SAL) FROM EMP e2 where e.DEPTNO = e2.DEPTNO GROUP BY DEPTNO);


