SELECT NAME FROM PLAYERS where
PLAYERNO IN (SELECT PLAYERNO FROM MATCHES where TEAMNO = 1)
AND 
PLAYERNO IN (SELECT PLAYERNO FROM MATCHES where TEAMNO = 2);

SELECT NAME, INITIALS FROM PLAYERS where PLAYERNO NOT IN
(SELECT PLAYERNO FROM PENALTIES where to_char(PEN_DATE, 'yyyy') = '1980');

SELECT * FROM PLAYERS where PLAYERNO IN (SELECT PLAYERNO FROM PENALTIES where AMOUNT > 80);

SELECT * FROM PLAYERS where PLAYERNO 
IN (SELECT PLAYERNO FROM PENALTIES where AMOUNT > 80) 
AND PLAYERNO NOT IN (SELECT PLAYERNO FROM PENALTIES where AMOUNT <= 80);

SELECT * FROM EMP e where SAL > 
(SELECT AVG(SAL) FROM EMP e2 where e.DEPTNO = e2.DEPTNO GROUP BY DEPTNO);

SELECT d.* FROM DEPT d where d.DEPTNO NOT IN
(SELECT e.DEPTNO FROM EMP e);

SELECT d.* FROM DEPT d where d.DEPTNO IN
(SELECT e.DEPTNO FROM EMP e where e.SAL > 1000);

SELECT d.* FROM DEPT d where d.DEPTNO IN
(SELECT e.DEPTNO FROM EMP e where e.SAL > 1000)
AND d.DEPTNO NOT IN
(SELECT DEPTNO FROM EMP where SAL < 1000);

